-- ============================================================
-- Reset crew table and insert new crew data
-- Run on VPS: mysql -u marine-dev -p nama_mrn < insert_crew.sql
-- ============================================================

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE crew_checkins;
TRUNCATE TABLE crew_assignments;
TRUNCATE TABLE crew;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO crew (name, role, phone, id_number, notes, qr_code, active, created_at, updated_at) VALUES
('ROZIM',          'captain', '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('TEMON',          'abk',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('DANI',           'captain', '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ANDI',           'captain', '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ROJI',           'kkm',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('BUDI',           'kkm',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ICHA',           'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('MICHELLE',       'captain', '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('HAMKA',          'kkm',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('PIAN',           'abk',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ANDI GRO',       'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('JEK',            'abk',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ANDRO',          'kkm',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('RIDWAN',         'captain', '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('MULYADI FL',     'abk',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('AHMAD FL',       'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('SYAFIQ FL',      'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ROBI FL',        'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('YUSUF FL',       'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('BRAGI FL',       'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('RIDWAN FL',      'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('AZIZAH FL',      'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('RISTON FL',      'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ASHADI FL',      'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('MARIA FL',       'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('JUMALI FL',      'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ISMAIL FL',      'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('HAFIZ FL',       'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ANDI DEWA FL',   'captain', '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('JUMALI FL CAPT', 'captain', '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('MAHFUD FL',      'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('NEJAR FL',       'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('IHROM FL',       'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('SAFIQ CAPT FL',  'captain', '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('SANDI FL',       'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('DIAZ FL',        'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('FAISAL FL',      'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('JUNAEDI CAPT FL','captain', '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('TABRANI FL',     'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('NURINSAN FL',    'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('RONAL FL',       'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('TUSMAN FL',      'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('YADI',           'captain', '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('REY FL',         'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('TORI FL',        'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('FATHIR JULIO',   'abk',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('SALIM FL',       'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('AMSAR CAPT FL',  'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('YUMI FL',        'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('KIBLI CAPT FL',  'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('YANA FL',        'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ABU HASAN CAPT FL','gro',   '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ROY',            'kkm',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('WIDI',           'kkm',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('IBING FL',       'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('YANTO FL',       'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('DARYANTO FL',    'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('IKHROM CAPT FL', 'captain', '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('AMRAN CAPT FL',  'captain', '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('RAFLI FL',       'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('MUNIR FL',       'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('EPUL FL',        'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('RAHMAN FL',      'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('JOHAN CAPT FL',  'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('SALOMO',         'abk',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ZEN CAPT FL',    'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('RIFKY FL',       'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('NANA',           'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('AGUNG FL',       'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('RAHMAT FL',      'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('SAPTA FL',       'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('SAIDI CAPT FL',  'captain', '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('LEMAN CAPT FL',  'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('RISKY FL',       'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ARIL FL',        'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ANGGA FL',       'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('IRFAN FL',       'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('MUS FL',         'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ANDRI FL',       'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ACANG',          'captain', '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('HELMY FL',       'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('LEMAN FL',       'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('FAJAR FL',       'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ODO FL',         'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('NABIL FL',       'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('ARIF FL',        'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('NANA FL',        'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('SYARIF GRO',     'gro',     '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('SAMAT FL',       'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW()),
('EDI FL',         'fl',      '', '', '', CONCAT('CREW_', UPPER(HEX(RANDOM_BYTES(8)))), 1, NOW(), NOW());

-- Update enum to include kkm and fl
ALTER TABLE crew MODIFY COLUMN role ENUM('captain','abk','gro','kkm','fl','staff','other') DEFAULT 'abk';

SELECT COUNT(*) as total_crew FROM crew;
